### ISSUE TITLE
Electron Edge JS Quickstart not runs in .Net 6 environment

### ISSUE THREAD

**Issue by selvamM** [agracio/electron-edge-js-quick-start#12]
We are trying to run electron edge js quick start sample in .Net 6 environment.

Steps we followed

1) Installed .NET 6 Run time installer

2) Extracted and tried running source we get an error. If we uninstall .Net 6 run time installer source runs without any issue.

Can you please confirm electron edge js is compatible with .NET 6 environment?

Error we faced.

`Uncaught TypeError: edge.initializeClrFunc is not a function
at Object.exports.func (C:\Users\demo\Downloads\electron-edge-js-quick-start-master (/C:/Users/demo/Downloads/electron-edge-js-quick-start-master%20(2)/electron-edge-js-quick-start-master/2)\electron-edge-js-quick-start-master\node_modules\electron-edge-js\lib\edge.js:192:17)
at Object.<anonymous> (C:\Users\demo\Downloads\electron-edge-js-quick-start-master (/C:/Users/demo/Downloads/electron-edge-js-quick-start-master%20(2)/electron-edge-js-quick-start-master/2)\electron-edge-js-quick-start-master\renderer.js:19:34)
at Object.<anonymous> (C:\Users\demo\Downloads\electron-edge-js-quick-start-master (/C:/Users/demo/Downloads/electron-edge-js-quick-start-master%20(2)/electron-edge-js-quick-start-master/2)\electron-edge-js-quick-start-master\renderer.js:68:3)
at Module._compile (internal/modules/cjs/loader.js:1152)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173)
at Module.load (internal/modules/cjs/loader.js:992)
at Module._load (internal/modules/cjs/loader.js:885)
at Function.f._load (electron/js2c/asar_bundle.js:5)
at Module.require (internal/modules/cjs/loader.js:1032)
at require (internal/modules/cjs/helpers.js:72)`

**Comment by selvamM** [comment]
Can we have any updates? @agracio

**Comment by agracio** [comment]
Did you run both `npm-install` and `dotnet build src/QuickStart.sln` **_after_** installing .net 6?

**Comment by selvamM** [comment]
@agracio  Yes we run npn-install and dotnet build src/QuickStart.sln and still we face. Can you confirm from your end as well?

**Comment by agracio** [comment]
Try [https://github.com/agracio/edge-js-quick-start](https://github.com/agracio/edge-js-quick-start) and let me know if you get the following message: `CoreClrEmbedding::Initialize - Could not resolve CoreCLR path. `

**Comment by selvamM** [comment]
@agracio We tried running source - https://github.com/agracio/edge-js-quick-start and faced issue as mentioned above

`Uncaught TypeError: edge.initializeClrFunc is not a function at Object.exports.func (C:\Users\demo\Downloads\electron-edge-js-quick-start-master (/C:/Users/demo/Downloads/electron-edge-js-quick-start-master%20(2)/electron-edge-js-quick-start-master/2)\electron-edge-js-quick-start-master\node_modules\electron-edge-js\lib\edge.js:192:17) at Object.<anonymous> (C:\Users\demo\Downloads\electron-edge-js-quick-start-master (/C:/Users/demo/Downloads/electron-edge-js-quick-start-master%20(2)/electron-edge-js-quick-start-master/2)\electron-edge-js-quick-start-master\renderer.js:19:34) at Object.<anonymous> (C:\Users\demo\Downloads\electron-edge-js-quick-start-master (/C:/Users/demo/Downloads/electron-edge-js-quick-start-master%20(2)/electron-edge-js-quick-start-master/2)\electron-edge-js-quick-start-master\renderer.js:68:3) at Module._compile (internal/modules/cjs/loader.js:1152) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173) at Module.load (internal/modules/cjs/loader.js:992) at Module._load (internal/modules/cjs/loader.js:885) at Function.f._load (electron/js2c/asar_bundle.js:5) at Module.require (internal/modules/cjs/loader.js:1032) at require (internal/modules/cjs/helpers.js:72)`

**Comment by Jerry239** [comment]
Same issue here. Tried on Windows 10 and a fresh Ubuntu 22.x

I get a couple of warnings. No errors tho.
Here's the build output:
`electron-edge-js-quick-start>dotnet build src\QuickStart.sln
Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): war
ning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the fu
ture. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [D:\GIT\electro
n-edge-js-quick-start\src\ExternalLibrary\ExternalLibrary.csproj]
C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): war
ning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the fu
ture. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [D:\GIT\electro
n-edge-js-quick-start\src\QuickStart.Core\QuickStart.Core.csproj]
  Restored D:\GIT\electron-edge-js-quick-start\src\ExternlaLibrary.Standard\ExternlaLibrary.Standard.csproj (in 159 ms)
  .
  Restored D:\GIT\electron-edge-js-quick-start\src\QuickStart.Standard\QuickStart.Standard.csproj (in 431 ms).
  2 of 4 projects are up-to-date for restore.
C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): war
ning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the fu
ture. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [D:\GIT\electro
n-edge-js-quick-start\src\ExternalLibrary\ExternalLibrary.csproj]
  ExternalLibrary -> D:\GIT\electron-edge-js-quick-start\src\ExternalLibrary\bin\Debug\netcoreapp2.0\ExternalLibrary.dl
  l
C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): war
ning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the fu
ture. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [D:\GIT\electro
n-edge-js-quick-start\src\QuickStart.Core\QuickStart.Core.csproj]
  QuickStart.Core -> D:\GIT\electron-edge-js-quick-start\src\QuickStart.Core\bin\Debug\netcoreapp2.0\QuickStart.Core.dl
  l
  ExternlaLibrary.Standard -> D:\GIT\electron-edge-js-quick-start\src\ExternlaLibrary.Standard\bin\Debug\netstandard2.0
  \ExternlaLibrary.Standard.dll
D:\GIT\electron-edge-js-quick-start\src\QuickStart.Standard\LocalMethods.cs(10,35): warning CS1998: This async method l
acks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls,
 or 'await Task.Run(...)' to do CPU-bound work on a background thread. [D:\GIT\electron-edge-js-quick-start\src\QuickSt
art.Standard\QuickStart.Standard.csproj]
D:\GIT\electron-edge-js-quick-start\src\QuickStart.Standard\LocalMethods.cs(15,35): warning CS1998: This async method l
acks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls,
 or 'await Task.Run(...)' to do CPU-bound work on a background thread. [D:\GIT\electron-edge-js-quick-start\src\QuickSt
art.Standard\QuickStart.Standard.csproj]
D:\GIT\electron-edge-js-quick-start\src\QuickStart.Standard\LocalMethods.cs(20,35): warning CS1998: This async method l
acks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls,
 or 'await Task.Run(...)' to do CPU-bound work on a background thread. [D:\GIT\electron-edge-js-quick-start\src\QuickSt
art.Standard\QuickStart.Standard.csproj]
  QuickStart.Standard -> D:\GIT\electron-edge-js-quick-start\src\QuickStart.Standard\bin\Debug\netstandard2.0\QuickStar
  t.Standard.dll

Build succeeded.

C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): war
ning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the fu
ture. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [D:\GIT\electro
n-edge-js-quick-start\src\ExternalLibrary\ExternalLibrary.csproj]
C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): war
ning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the fu
ture. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [D:\GIT\electro
n-edge-js-quick-start\src\QuickStart.Core\QuickStart.Core.csproj]
C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): war
ning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the fu
ture. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [D:\GIT\electro
n-edge-js-quick-start\src\ExternalLibrary\ExternalLibrary.csproj]
C:\Program Files\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): war
ning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the fu
ture. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [D:\GIT\electro
n-edge-js-quick-start\src\QuickStart.Core\QuickStart.Core.csproj]
D:\GIT\electron-edge-js-quick-start\src\QuickStart.Standard\LocalMethods.cs(10,35): warning CS1998: This async method l
acks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls,
 or 'await Task.Run(...)' to do CPU-bound work on a background thread. [D:\GIT\electron-edge-js-quick-start\src\QuickSt
art.Standard\QuickStart.Standard.csproj]
D:\GIT\electron-edge-js-quick-start\src\QuickStart.Standard\LocalMethods.cs(15,35): warning CS1998: This async method l
acks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls,
 or 'await Task.Run(...)' to do CPU-bound work on a background thread. [D:\GIT\electron-edge-js-quick-start\src\QuickSt
art.Standard\QuickStart.Standard.csproj]
D:\GIT\electron-edge-js-quick-start\src\QuickStart.Standard\LocalMethods.cs(20,35): warning CS1998: This async method l
acks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls,
 or 'await Task.Run(...)' to do CPU-bound work on a background thread. [D:\GIT\electron-edge-js-quick-start\src\QuickSt
art.Standard\QuickStart.Standard.csproj]
    7 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.50`

**Comment by Jerry239** [comment]
BTW, any chance to get an update to support current electronjs (19.x)?
Would be much appreciated

**Comment by selvamM** [comment]
@agracio Have you tried running [quick start sample](https://github.com/agracio/electron-edge-js-quick-start) in .NET 6 environment?

**Comment by selvamM** [comment]
@agracio Can you please provided updates as we cannot proceed further.

**Comment by selvamM** [comment]
@agracio Any updates?

**Comment by agracio** [comment]
Unfortunately the re seems to be an issue with .net 6 hash resolution in edge-js code, no ETA  for now.

**Comment by selvamM** [comment]
@agracio Any updates on when can we get the support?

**Comment by agracio** [comment]
Issue resolved however in order for fix to work on Windows all `electron-edge-js` libraries have to be recompiled. Currently I am unable to do that.

**Comment by selvamM** [comment]
@agracio Can we get some  timeline to make get an working version?

**Comment by agracio** [comment]
Fixed
