### ISSUE TITLE
Issue while running electron-edge-js-quick-start in Mac

### ISSUE THREAD

**Issue by MaheshwariMariyappan** [agracio/electron-edge-js-quick-start#15]
We are trying to run electron edge js quick start sample in .Net 6/.Net3/.Net2/.Net1 environment in Mac.

Steps we followed

- Installed above versions of .NET Run time installer
- Extracted and tried running source.
- We ran npm install and npm start
- We're getting the below error.

Error we faced.

![image](https://user-images.githubusercontent.com/92787755/205031020-430bb685-640e-48f0-8fa3-256c3ba2e4a0.png)

**Comment by agracio** [comment]
macOS issue: https://github.com/agracio/electron-edge-js?tab=readme-ov-file#macos
