### ISSUE TITLE
System.TypeInitializationException error

### ISSUE THREAD

**Issue by Vitaliy-Gorokhovskiy** [agracio/electron-edge-js-quick-start#2]
Hello,
I really hope if you could help me out with this.

I've used the "Quick start for electron-edge-js module using .NET Core" to get started and it works fine, so I've  added Couchbase Lite 2.0.0-db021 (which is a no-sql offline db), and everything runs fine in the library when executed via Unit Test or console app. However, when I attempt to call it from  electron-edge-js app I get an exception (see below).

Steps to replicate: Add nuget package for "Couchbase Lite" and "Couchbase.Lite.Support.NetDesktop" (http://mobile.nuget.couchbase.com/nuget/Developer/) "pre-release" to "QuickStart.Core" sample project.

under LocalMethods

 public async Task<object> GetAppDomainDirectory(dynamic input)
        {
           Couchbase.Lite.Support.NetDesktop.Activate();
           Couchbase.Lite.Logging.Log.Disabled = true; // throws exception here 

          return AppDomain.CurrentDomain.BaseDirectory;
      }

Message
:
"An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)"
Name
:
"System.BadImageFormatException"
Source
:
"System.Private.CoreLib"
StackTrace
:
"   at System.Runtime.Loader.AssemblyLoadContext.InternalLoadUnmanagedDllFromPath(String unmanagedDllPath)
↵   at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext)
↵   at LiteCore.Interop.Native.c4log_getDomain(String name, Boolean create)
↵   at Couchbase.Lite.Logging.Log..cctor() in C:\jenkins\workspace\couchbase-lite-net\couchbase-lite-net\src\Couchbase.Lite\Log\Log.cs:line 48"

**Comment by agracio** [comment]
This usually indicates incompatible architecture i.e. using x86 image in x64 app and vice versa.

**Comment by Vitaliy-Gorokhovskiy** [comment]
Thanks for quick reply. I tried changing Build Platform target from x64/Any CPU to x86, and nothing works (even the sample functions) I get below exception. A quick note if I embed the c# code inside javascript it works fine, it only seems to affect the dll. I feel like I'm missing something simple, just can't figure out what.


"Could not load file or assembly 'QuickStart.Core, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format."
Name
:
"System.BadImageFormatException"
Source
:
"System.Private.CoreLib"
StackTrace
:
"   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
↵   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, IntPtr ptrLoadContextBinder)
↵   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
↵   at CoreCLREmbedding.EdgeAssemblyResolver.LoadDependencyManifest(String dependencyManifestFile)
↵   at CoreCLREmbedding.Initialize(IntPtr context, IntPtr exception)"

**Comment by agracio** [comment]
In that case lets try to take it one step at a time. What happens when you do a fresh check out of this repo and start it using the instruction in README? That should work without a problem. 
Once it starts working again try adding libraries to it.

**Comment by agracio** [comment]
What OS are you using?

**Comment by Vitaliy-Gorokhovskiy** [comment]
Windows 10 Enterprise. I just pulled the quick start project again, followed the readme file. Everything works fine, if I switch the build runtime to x86 nothing works and I get exception "Could not load file or assembly 'QuickStart.Core, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format."

If I put it back to Any CPU it's all good. if I add the couchbase packages and run it as Any CPU it breaks on the Couchbase.Lite.Logging.Log. Same as before...

**Comment by agracio** [comment]
Are you sure you adding .NET Core 2.0 Couchbase dll?
Update: Trying it myself, will update shortly.

**Comment by Vitaliy-Gorokhovskiy** [comment]
yes, the project located here https://developer.couchbase.com/documentation/mobile/2.0/couchbase-lite/csharp.html

By the way, the same function works fine inside electron:
```js
function callEdgeDll() {
    var inlineC = edge.func({
        source: function () {/* 
        using System.Threading.Tasks;

        public class Startup
        {
            public async Task<object> Invoke(object input)
            {
                Couchbase.Lite.Support.NetDesktop.Activate();
                Couchbase.Lite.Logging.Log.Disabled = true;

                return "Test";
            }
        }
    */},
        references: ['Couchbase.Lite.dll', 'Couchbase.Lite.Support.NetDesktop.dll']
    });

    inlineC(null, function (e, r) {
        if (e) throw error;
        console.log(r);
    });
}
```

**Comment by agracio** [comment]
Not really sure about this one, `Couchbase.Lite.Support.NetDesktop.Activate();` works fine but next line throws exception. Perhaps there is something wrong with pre-release library? 
Doesn't explain why it works fine when used inline though.

Edit: The problem appears to be related to unmanaged LiteCore.dll. For now the only thing I can suggest is to try and use inline code and see if it actually works when interacting with DB.

**Comment by tvoumat** [comment]
Thank you for your time. Do you think it's worth the effort to get couchbase devs involved?
