### ISSUE TITLE
Loading external .Net library

### ISSUE THREAD

**Issue by DionDavid** [agracio/electron-edge-js-quick-start#3]
Dear agracio,

I want to load in an external library but I can't get it to work.
The library that I want to load in is the DocX .Net library: [DocX](https://github.com/xceedsoftware/DocX)

The library is built with Visual Studio 2017

This is the code that I use:
![image](https://user-images.githubusercontent.com/36475150/37835544-b06bb984-2eb0-11e8-887a-087da1f88216.png)

And this is the error that I get:

Error at Objects.exports.func. It seems to come from line 8.

Can you explain me how to do this the right way?

Yours Sincerely,

DionDavid

**Comment by agracio** [comment]
What is the full error you getting? To me it appears that `module.exports` might be causing a problem.
On a separate note all C# methods that Edge.js interacts with should have `public async Task<object> Invoke(dynamic input)` signature.

**Comment by DionDavid** [comment]
Oh I'm still quite new to .Net so I thought loading in all libraries was possible. Thank you for explaining. I will write it myself then.

**Comment by DionDavid** [comment]
I am running your electron-edge-js-quick-start and I get two different errors. 

On Mac I get the error: CoreClrEmbedding::Initialize - Failed to initialize CoreCLR, HRESULT: 0x80070057.

On Windows I get the error: Error: %1 is not a valid Win32 application

I built the project with VS2017.

Do you know what I can do to fix this?

**Comment by agracio** [comment]
Lets start with Windows. 
I realised that instructions in README are in the wrong order, you need to `npm install` first before building the project.
Try pulling a fresh copy of the repo and follow the instructions.

**Comment by DionDavid** [comment]
Alright, I did what you said but it results into the same error.

**Comment by agracio** [comment]
What version of Windows and architecture you have 32 or 64 bit?

**Comment by DionDavid** [comment]
I have windows 10 64bit

**Comment by agracio** [comment]
This error usually indicates version compatibility problem, like trying to use 32 bit dll in 64 bit project or vice versa. Not sure what is going on with it in your case.
