### ISSUE TITLE
node version mismatch

### ISSUE THREAD

**Issue by vadi2** [agracio/electron-edge-js-quick-start#4]
I'm getting this when running either electron-edge-js or electron-edge-js-quick-start on Ubuntu 17.10:

```
Uncaught Error: The module '/home/vadi/Programs/electron-edge-js-quick-start/node_modules/electron-edge-js/build/Release/edge_coreclr.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

node version is 6.12.3. What could be the issue?

**Comment by vadi2** [comment]
Had to upgrade to node 8.x - [Ubuntu instructions here](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions).

After upgrading, do:

```
npm rebuild electron-edge-js --update-binary
```

**Comment by agracio** [comment]
`electron-edge-js` does not use Node.js installed on your system, it uses Node.js packaged with Electron.
